"""
Project Euler Problem 2
=======================

Each new term in the Fibonacci sequence is generated by adding the
previous two terms. By starting with 1 and 2, the first 10 terms will be:

                  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

Find the sum of all the even-valued terms in the sequence which do not
exceed four million.
"""


def problem2(limit):
    result = 0
    fib, last = 2, 1

    while fib <= limit:
        if fib % 2 == 0:
            result += fib

        fib, last = fib + last, fib

    return result


if __name__ == '__main__':
    print problem2(4000000)
